### ISSUE TITLE
Output Dislay

### ISSUE THREAD

**Issue by MathematicsCLtd** [SmartColumbusBeta/ohio-legislature#1]
@bbalser and @jdenen I can't figure out how to upload my notebook with the Output visible. I'd like it to show without you having to download and run the code yourself.

**Comment by jdenen** [comment]
I don't think this is possible in GitHub:

https://help.github.com/articles/working-with-jupyter-notebook-files-on-github/

I'm guessing you'll need to convert it to HTML (or markdown) and upload that.
